# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2afc3e1a531b9d20d35130309fc60348ae8cf807bdda9f398fd099b051d51a0a6207b60b66b1522fd95ad7ec982ebbb14e94472e5f10ec2968a334d982a920d2

test:
  secret_key_base: 6b6b6c144a373cc424f9dbfb4e8730a13aa49e659f575ce873b0a17e429045fd943136d8decb9bdfc8a3b79047add64eea857292dd25fbafd86504d8df4b5afa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
